[package]
name = "digest_auth_checker"
version = "0.1.0"
edition = "2021"
authors = [ "Matthias Wimmer <m@tthias.eu>"]

[dependencies]
clap = { version = "3.2.15", features = [ "derive" ] }
console = "0.15.1"
md5 = "0.7.0"